# Generated by Django 5.1.15 on 2026-09-24 01:39

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("website", models.URLField(blank=True)),
                ("crunchbase_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("expired", "Expired (re-verification due)"),
                            ("revoked", "Revoked"),
                        ],
                        default="verified",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founders",
                        to="verification.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founder_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=120)),
                ("company_domain", models.CharField(db_index=True, max_length=253)),
                ("work_email", models.EmailField(max_length=254)),
                ("role_title", models.CharField(max_length=80)),
                ("linkedin_url", models.URLField(blank=True)),
                ("crunchbase_url", models.URLField(blank=True)),
                (
                    "notes",
                    apps.common.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("email_pending", "Awaiting work-email confirmation"),
                            ("under_review", "Under human review"),
                            ("needs_info", "More information requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn / superseded"),
                        ],
                        db_index=True,
                        default="email_pending",
                        max_length=16,
                    ),
                ),
                (
                    "email_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("email_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["email_pending", "under_review", "needs_info"],
                            )
                        ),
                        fields=("user",),
                        name="one_open_verification_per_user",
                    )
                ],
            },
        ),
    ]
