# Generated by Django 5.1.15 on 2026-09-24 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hide_story", "Hide story"),
                            ("restore_story", "Restore story"),
                            ("remove_story", "Remove story"),
                            ("hide_comment", "Hide comment"),
                            ("approve_comment", "Approve held comment"),
                            ("suspend_user", "Suspend user"),
                            ("unsuspend_user", "Unsuspend user"),
                            ("dismiss_report", "Dismiss report"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_type", models.CharField(max_length=16)),
                ("target_id", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="engagement.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
