# Generated by Django 5.1.15 on 2026-09-24 01:39

import apps.accounts.models
import apps.common.fields
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "handle",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9](?:[a-z0-9_]{1,28}[a-z0-9])$",
                                "Handles are 3-30 chars: lowercase letters, digits and underscores.",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("bio", models.CharField(blank=True, max_length=280)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="reader",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "totp_secret",
                    apps.common.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("totp_enabled", models.BooleanField(default=False)),
                ("totp_last_used_step", models.BigIntegerField(default=0)),
                ("failed_login_count", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
