# Generated by Django 5.2.17 on 2026-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiredHandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle_hash", models.CharField(max_length=64, unique=True)),
                ("retired_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
