# Generated by Django 5.1.15 on 2026-09-24 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting upload"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("declared_type", models.CharField(max_length=32)),
                ("original_key", models.CharField(max_length=255)),
                ("display_key", models.CharField(blank=True, max_length=255)),
                ("thumb_key", models.CharField(blank=True, max_length=255)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("dominant_color", models.CharField(blank=True, max_length=7)),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=140)),
                (
                    "dek",
                    models.CharField(
                        blank=True, max_length=280, verbose_name="subtitle"
                    ),
                ),
                ("body_markdown", models.TextField(max_length=60000)),
                ("body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden by moderator"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("reading_minutes", models.PositiveSmallIntegerField(default=1)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("save_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("featured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stories.media",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="stories", to="stories.tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories",
            },
        ),
        migrations.CreateModel(
            name="StoryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=140)),
                ("dek", models.CharField(blank=True, max_length=280)),
                ("body_markdown", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("chain_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["story", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "number"), name="unique_story_revision"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "-published_at"], name="stories_sto_status_386c74_idx"
            ),
        ),
    ]
